# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-06 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=350, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('email', models.CharField(blank=True, max_length=350, null=True)),
                ('data_nasc', models.DateField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=14, null=True)),
            ],
            options={
                'db_table': 'aluno',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AlunoAssinatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_aluno', models.ForeignKey(blank=True, db_column='id_aluno', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Aluno')),
            ],
            options={
                'db_table': 'aluno_assinatura',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pagseguro', models.CharField(blank=True, max_length=500, null=True)),
                ('data_assi', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'assinatura',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=250, null=True)),
                ('url_aula', models.CharField(blank=True, max_length=500, null=True)),
                ('descricao', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'aula',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=250, null=True)),
                ('descricao', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'curso',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=250, null=True)),
                ('url_arquivo', models.CharField(blank=True, max_length=500, null=True)),
                ('descricao', models.CharField(blank=True, max_length=500, null=True)),
                ('id_aula', models.ForeignKey(blank=True, db_column='id_aula', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Aula')),
            ],
            options={
                'db_table': 'documento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Duvida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=250, null=True)),
                ('descricao', models.CharField(blank=True, max_length=750, null=True)),
                ('data_criacao', models.DateField(blank=True, null=True)),
                ('id_aula', models.ForeignKey(blank=True, db_column='id_aula', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Aula')),
            ],
            options={
                'db_table': 'duvida',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(blank=True, max_length=350, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('bairro', models.CharField(blank=True, max_length=250, null=True)),
                ('cidade', models.CharField(blank=True, max_length=250, null=True)),
                ('uf', models.CharField(blank=True, max_length=250, null=True)),
                ('pais', models.CharField(blank=True, max_length=250, null=True)),
                ('cep', models.CharField(blank=True, max_length=30, null=True)),
                ('complemento', models.CharField(blank=True, max_length=350, null=True)),
            ],
            options={
                'db_table': 'endereco',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=250, null=True)),
                ('descricao', models.CharField(blank=True, max_length=500, null=True)),
                ('id_curso', models.ForeignKey(blank=True, db_column='id_curso', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Curso')),
            ],
            options={
                'db_table': 'modulo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pagseguro', models.CharField(blank=True, max_length=500, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('periodo', models.CharField(blank=True, max_length=250, null=True)),
                ('id_curso', models.ForeignKey(blank=True, db_column='id_curso', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Curso')),
            ],
            options={
                'db_table': 'plano',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=350, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('data_nasc', models.DateField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=14, null=True)),
                ('id_endereco', models.ForeignKey(blank=True, db_column='id_endereco', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Endereco')),
            ],
            options={
                'db_table': 'professor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=750, null=True)),
                ('data_criacao', models.DateField(blank=True, null=True)),
                ('id_duvida', models.ForeignKey(blank=True, db_column='id_duvida', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Duvida')),
            ],
            options={
                'db_table': 'resposta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=500, null=True)),
                ('data_criacao', models.DateField(blank=True, null=True)),
                ('id_assinatura', models.ForeignKey(blank=True, db_column='id_assinatura', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Assinatura')),
            ],
            options={
                'db_table': 'situacao',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='id_professor',
            field=models.ForeignKey(blank=True, db_column='id_professor', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Professor'),
        ),
        migrations.AddField(
            model_name='aula',
            name='id_modulo',
            field=models.ForeignKey(blank=True, db_column='id_modulo', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Modulo'),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='id_plano',
            field=models.ForeignKey(blank=True, db_column='id_plano', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Plano'),
        ),
        migrations.AddField(
            model_name='alunoassinatura',
            name='id_assinatura',
            field=models.ForeignKey(blank=True, db_column='id_assinatura', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Assinatura'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='id_endereco',
            field=models.ForeignKey(blank=True, db_column='id_endereco', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Endereco'),
        ),
    ]
