# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-18 19:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=350, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('email', models.CharField(blank=True, max_length=350, null=True)),
                ('data_nasc', models.DateField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=14, null=True)),
                ('tipo_perfil', models.TextField(blank=True, null=True)),
                ('id_endereco', models.ForeignKey(blank=True, db_column='id_endereco', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.Endereco')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perfil',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PerfilAssinatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_assinatura', models.ForeignKey(blank=True, db_column='id_assinatura', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.Assinatura')),
                ('id_perfil', models.ForeignKey(blank=True, db_column='id_perfil', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.Perfil')),
            ],
            options={
                'db_table': 'perfil_assinatura',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='id_endereco',
        ),
        migrations.RemoveField(
            model_name='alunoassinatura',
            name='id_aluno',
        ),
        migrations.RemoveField(
            model_name='alunoassinatura',
            name='id_assinatura',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='id_endereco',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='id_professor',
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
        migrations.DeleteModel(
            name='AlunoAssinatura',
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
        migrations.AddField(
            model_name='curso',
            name='id_perfil',
            field=models.ForeignKey(blank=True, db_column='id_perfil', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.Perfil'),
        ),
    ]
