# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-18 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20171018_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='tipo_perfil',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
